// Generated by https://quicktype.io

export interface PublicationsTypesResponse {
    results: Results;
}

export interface Results {
    count:       number;
    totalPages:  number;
    currentPage: number;
    results:     Result[];
}

export interface Result {
    id:          number;
    name:        string;
    description: string;
    created_at:  string;
    updated_at:  string;
}
