// Generated by https://quicktype.io

export interface PublicationsResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  currentPage: number;
  results: Publication[];
}

export interface Publication {
  id: string;
  user_id: string;
  publication_type_id: number;
  city_id: number;
  title: string;
  description: Description;
  content: string;
  reference_link: string;
  created_at: string;
  updated_at: string;
  votes_count: number;
  user: User;
  publication_type: PublicationType;
  images: Image[];
  tags: PublicationType[];
}

export enum Description {
  ConciertoDeRock = 'Concierto de rock',
  Description = 'description',
  Prueba1 = 'prueba1',
}

export interface Image {
  publication_id: string;
  image_url: string;
  order: number;
  created_at: string;
  updated_at: string;
}

export interface PublicationType {
  id: number;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  image_url?: null;
}

export interface User {
  first_name: FirstName;
  last_name: LastName;
  image_url: null | string;
}

export enum FirstName {
  Julio = 'julio',
  Laura = 'Laura',
  NotAdmin = 'NotAdmin',
}

export enum LastName {
  Hello = 'Hello',
  Padrón = 'Padrón',
  Sanchez = 'sanchez',
}
